[package]
name = "rer-engine-2d"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[[bin]]
name = "rer_engine_2d"
path = "src/main.rs"

[dependencies]
winit.workspace = true
wgpu.workspace = true
pollster.workspace = true
glam.workspace = true
bytemuck.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
env_logger.workspace = true
gltf.workspace = true
image.workspace = true
rapier3d.workspace = true
rodio.workspace = true
getrandom.workspace = true
raw-window-handle.workspace = true
gilrs.workspace = true
rer-engine-shared = { path = "../engine_shared" }
rer-engine-ipc-common = { path = "../engine_ipc_common" }
ttf-parser.workspace = true
ab_glyph.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
x11.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows.workspace = true
