// ---------------------------------------------------------------------------
// Scripting — Lua 5.4 via mlua
//
// Architecture:
//   - ScriptEngine owns the Lua VM and all loaded scripts.
//   - Scripts are attached to entities: entity_id → Vec<Script>.
//   - Each Script has lifecycle functions: on_start(), update(dt), on_stop().
//   - Commands generated by Lua (move, play_anim, etc.) are collected into a
//     Vec<ScriptCmd> returned from tick(). The caller (State::update) applies them.
//   - The Lua VM is sandboxed: no io, no os.execute, no require from filesystem.
// ---------------------------------------------------------------------------

use std::collections::HashMap;
use mlua::prelude::*;

// ---------------------------------------------------------------------------
// Commands that Lua scripts can request from the engine
// ---------------------------------------------------------------------------
#[derive(Debug, Clone)]
pub enum ScriptCmd {
    /// Move entity to absolute position (world units).
    SetPosition { id: u32, x: f32, y: f32 },
    /// Translate entity by a delta (world units per call).
    Translate { id: u32, dx: f32, dy: f32 },
    /// Set entity scale uniformly.
    SetScale { id: u32, sx: f32, sy: f32 },
    /// Play a named animation on an entity.
    PlayAnimation { id: u32, name: String },
    /// Stop the current animation on an entity.
    StopAnimation { id: u32 },
    /// Enable or disable physics on an entity.
    /// `body_type` is only used when `enabled = true` (e.g. "dynamic", "static").
    SetPhysics { id: u32, enabled: bool, body_type: String },
    /// Move a physics-enabled entity using linear velocity so Rapier resolves
    /// collisions naturally. `speed` is in world units/second; `dir_x`/`dir_y`
    /// form the movement direction (normalized internally).
    MoveEntity { id: u32, speed: f32, dir_x: f32, dir_y: f32 },
    /// Stop a physics-enabled entity instantly by zeroing its linear and
    /// angular velocities. Useful to prevent inertia drift after movement ends.
    StopEntity { id: u32 },
    /// Log a message to the engine console (forwarded via IPC).
    Log { message: String },
}

// ---------------------------------------------------------------------------
// A single loaded script attached to an entity
// ---------------------------------------------------------------------------
struct Script {
    /// Script source path (for error messages).
    path: String,
    /// Lua table holding the script's state and functions.
    /// Shape: { on_start=fn, update=fn(dt), on_stop=fn, ... user fields }
    table: LuaTable,
    /// Whether on_start() has been called already.
    started: bool,
}

// ---------------------------------------------------------------------------
// Per-entity read-only snapshot passed to scripts each tick
// ---------------------------------------------------------------------------
#[derive(Debug, Clone)]
pub struct EntitySnapshot {
    pub id:       u32,
    pub x:        f32,
    pub y:        f32,
    pub scale_x:  f32,
    pub scale_y:  f32,
    /// Names of animations available for this entity.
    pub animations: Vec<String>,
}

// ---------------------------------------------------------------------------
// ScriptEngine
// ---------------------------------------------------------------------------
pub struct ScriptEngine {
    lua: Lua,
    /// entity_id → list of scripts attached to it.
    scripts: HashMap<u32, Vec<Script>>,
}

impl ScriptEngine {
    pub fn new() -> LuaResult<Self> {
        let lua = Lua::new();

        // ── Sandbox: remove dangerous stdlib modules ──────────────────────
        {
            let globals = lua.globals();
            // Remove filesystem/process access
            globals.set("io",      LuaNil)?;
            globals.set("os",      LuaNil)?;
            globals.set("package", LuaNil)?;
            globals.set("require", LuaNil)?;
            globals.set("dofile",  LuaNil)?;
            globals.set("loadfile", LuaNil)?;
            // Keep: math, string, table, pairs, ipairs, tostring, tonumber, print
        }

        Ok(Self {
            lua,
            scripts: HashMap::new(),
        })
    }

    // ── Script loading ────────────────────────────────────────────────────

    /// Load a Lua script from source code and attach it to `entity_id`.
    /// The script must return a table (or set a global named after the file).
    /// Expected shape:
    /// ```lua
    /// local script = {}
    /// function script.on_start(self)  end
    /// function script.update(self, dt) end
    /// function script.on_stop(self)   end
    /// return script
    /// ```
    pub fn attach_script(&mut self, entity_id: u32, path: &str, source: &str) -> LuaResult<()> {
        // Each script runs in its own chunk; the returned value must be a table.
        let chunk = self.lua.load(source).set_name(path);
        let table: LuaTable = chunk.eval()?;

        let script = Script {
            path: path.to_string(),
            table,
            started: false,
        };

        self.scripts.entry(entity_id).or_default().push(script);
        log::info!("[scripting] script '{}' adjuntado a entidad {}", path, entity_id);
        Ok(())
    }

    /// Remove all scripts attached to an entity (e.g. when it is deleted).
    pub fn detach_entity(&mut self, entity_id: u32) {
        if let Some(scripts) = self.scripts.remove(&entity_id) {
            for s in &scripts {
                self.call_lifecycle(&s.table, "on_stop", entity_id);
            }
            log::info!("[scripting] scripts de entidad {} removidos", entity_id);
        }
    }

    /// Remove only animation scripts (path prefix `$anim$::`) from an entity.
    /// Entity-level scripts loaded via `LoadScript` are left intact.
    pub fn detach_animation_scripts(&mut self, entity_id: u32) {
        // Collect tables first (immutable access ends before the mutable retain below)
        let anim_tables: Vec<LuaTable> = self.scripts
            .get(&entity_id)
            .map(|scripts| {
                scripts.iter()
                    .filter(|s| s.path.starts_with("$anim$::"))
                    .map(|s| s.table.clone())
                    .collect()
            })
            .unwrap_or_default();

        let count = anim_tables.len();
        for table in &anim_tables {
            self.call_lifecycle(table, "on_stop", entity_id);
        }

        if let Some(scripts) = self.scripts.get_mut(&entity_id) {
            scripts.retain(|s| !s.path.starts_with("$anim$::"));
        }
        if count > 0 {
            log::info!("[scripting] {} script(s) de animación removidos de entidad {}", count, entity_id);
        }
    }

    /// Returns the list of entity IDs that have at least one script attached.
    pub fn entity_ids(&self) -> Vec<u32> {
        self.scripts.keys().copied().collect()
    }

    // ── Tick ──────────────────────────────────────────────────────────────

    /// Called every frame. Snapshots are the current state of all entities
    /// (position, scale, available animations). Returns the list of commands
    /// the scripts want to execute — caller applies them to State.
    pub fn tick(
        &mut self,
        dt: f32,
        snapshots: &HashMap<u32, EntitySnapshot>,
    ) -> Vec<ScriptCmd> {
        // Shared command queue: Lua functions append here via a Lua-side table
        // that we read back after all scripts run.
        let cmd_queue: LuaTable = self.lua.create_table().expect("tabla cmd_queue");
        self.lua.globals().set("__cmds", cmd_queue).expect("set __cmds");

        // Register helpers into globals before each tick (cheap: just sets refs)
        self.register_api(snapshots);

        let mut commands = Vec::new();

        let entity_ids: Vec<u32> = self.scripts.keys().copied().collect();
        for entity_id in entity_ids {
            let snapshot = snapshots.get(&entity_id).cloned();

            // Build the `entity` table passed to on_start/update
            let entity_table = match self.build_entity_table(entity_id, snapshot.as_ref()) {
                Ok(t) => t,
                Err(e) => {
                    log::error!("[scripting] error construyendo entity table {}: {}", entity_id, e);
                    continue;
                }
            };

            let scripts = self.scripts.get_mut(&entity_id).expect("entity scripts");
            for script in scripts.iter_mut() {
                if !script.started {
                    script.started = true;
                    if let Err(e) = call_fn(&script.table, "on_start", entity_table.clone()) {
                        log::warn!("[scripting] on_start '{}': {}", script.path, e);
                    }
                }
                if let Err(e) = call_fn_dt(&script.table, "update", entity_table.clone(), dt) {
                    log::warn!("[scripting] update '{}': {}", script.path, e);
                }
            }
        }

        // Collect commands from __cmds queue
        if let Ok(queue) = self.lua.globals().get::<LuaTable>("__cmds") {
            for pair in queue.sequence_values::<LuaTable>() {
                if let Ok(cmd_table) = pair {
                    if let Ok(cmd) = parse_cmd_table(cmd_table) {
                        commands.push(cmd);
                    }
                }
            }
        }

        commands
    }

    // ── Internal helpers ──────────────────────────────────────────────────

    /// Register engine API functions into Lua globals.
    /// These are re-registered each tick so closures capture fresh data.
    fn register_api(&self, snapshots: &HashMap<u32, EntitySnapshot>) {
        let globals = self.lua.globals();
        let lua = &self.lua;

        // engine.move_to(id, x, y)
        let move_to = lua.create_function(|lua_ctx, (id, x, y): (u32, f32, f32)| {
            push_cmd(lua_ctx, "move_to", |t| {
                t.set("id", id)?;
                t.set("x",  x)?;
                t.set("y",  y)?;
                Ok(())
            })
        }).expect("create move_to fn");
        let _ = globals.set("__api_move_to", move_to);

        // engine.translate(id, dx, dy)
        let translate = lua.create_function(|lua_ctx, (id, dx, dy): (u32, f32, f32)| {
            push_cmd(lua_ctx, "translate", |t| {
                t.set("id", id)?;
                t.set("dx", dx)?;
                t.set("dy", dy)?;
                Ok(())
            })
        }).expect("create translate fn");
        let _ = globals.set("__api_translate", translate);

        // engine.set_scale(id, sx, sy)
        let set_scale = lua.create_function(|lua_ctx, (id, sx, sy): (u32, f32, f32)| {
            push_cmd(lua_ctx, "set_scale", |t| {
                t.set("id", id)?;
                t.set("sx", sx)?;
                t.set("sy", sy)?;
                Ok(())
            })
        }).expect("create set_scale fn");
        let _ = globals.set("__api_set_scale", set_scale);

        // engine.play_animation(id, name)
        let play_animation = lua.create_function(|lua_ctx, (id, name): (u32, String)| {
            push_cmd(lua_ctx, "play_animation", |t| {
                t.set("id",   id)?;
                t.set("name", name)?;
                Ok(())
            })
        }).expect("create play_animation fn");
        let _ = globals.set("__api_play_animation", play_animation);

        // engine.stop_animation(id)
        let stop_animation = lua.create_function(|lua_ctx, id: u32| {
            push_cmd(lua_ctx, "stop_animation", |t| {
                t.set("id", id)?;
                Ok(())
            })
        }).expect("create stop_animation fn");
        let _ = globals.set("__api_stop_animation", stop_animation);

        // engine.set_physics(id, enabled, body_type?)
        // body_type es opcional; si se omite se usa "dynamic" al re-habilitar.
        let set_physics = lua.create_function(|lua_ctx, (id, enabled, body_type): (u32, bool, Option<String>)| {
            push_cmd(lua_ctx, "set_physics", |t| {
                t.set("id",        id)?;
                t.set("enabled",   enabled)?;
                t.set("body_type", body_type.unwrap_or_else(|| "dynamic".to_string()))?;
                Ok(())
            })
        }).expect("create set_physics fn");
        let _ = globals.set("__api_set_physics", set_physics);

        // engine.move_entity(id, speed, dir_x, dir_y)
        // Mueve la entidad con física aplicando velocidad lineal; Rapier resuelve
        // las colisiones correctamente. dir_x/dir_y forman el vector de dirección.
        let move_entity = lua.create_function(|lua_ctx, (id, speed, dir_x, dir_y): (u32, f32, f32, f32)| {
            push_cmd(lua_ctx, "move_entity", |t| {
                t.set("id",    id)?;
                t.set("speed", speed)?;
                t.set("dir_x", dir_x)?;
                t.set("dir_y", dir_y)?;
                Ok(())
            })
        }).expect("create move_entity fn");
        let _ = globals.set("__api_move_entity", move_entity);

        // engine.stop_entity(id)
        let stop_entity = lua.create_function(|lua_ctx, id: u32| {
            push_cmd(lua_ctx, "stop_entity", |t| {
                t.set("id", id)?;
                Ok(())
            })
        }).expect("create stop_entity fn");
        let _ = globals.set("__api_stop_entity", stop_entity);

        // engine.log(msg)
        let log_fn = lua.create_function(|lua_ctx, msg: String| {
            push_cmd(lua_ctx, "log", |t| {
                t.set("message", msg)?;
                Ok(())
            })
        }).expect("create log fn");
        let _ = globals.set("__api_log", log_fn);

        // engine table: the public API that scripts use
        // engine.move_to, engine.translate, etc.
        let engine_table = lua.create_table().expect("engine table");
        let _ = engine_table.set("move_to",       globals.get::<LuaFunction>("__api_move_to").ok());
        let _ = engine_table.set("translate",      globals.get::<LuaFunction>("__api_translate").ok());
        let _ = engine_table.set("set_scale",      globals.get::<LuaFunction>("__api_set_scale").ok());
        let _ = engine_table.set("play_animation", globals.get::<LuaFunction>("__api_play_animation").ok());
        let _ = engine_table.set("stop_animation", globals.get::<LuaFunction>("__api_stop_animation").ok());
        let _ = engine_table.set("set_physics",    globals.get::<LuaFunction>("__api_set_physics").ok());
        let _ = engine_table.set("move_entity",    globals.get::<LuaFunction>("__api_move_entity").ok());
        let _ = engine_table.set("stop_entity",    globals.get::<LuaFunction>("__api_stop_entity").ok());
        let _ = engine_table.set("log",            globals.get::<LuaFunction>("__api_log").ok());
        let _ = globals.set("engine", engine_table);

        // Inject entity snapshots as a read-only table (entities[id] = {x,y,...})
        let entities_table = lua.create_table().expect("entities table");
        for (id, snap) in snapshots {
            let t = lua.create_table().expect("snap table");
            let _ = t.set("id",      snap.id);
            let _ = t.set("x",       snap.x);
            let _ = t.set("y",       snap.y);
            let _ = t.set("scale_x", snap.scale_x);
            let _ = t.set("scale_y", snap.scale_y);
            let anims = lua.create_table().expect("anims table");
            for (i, name) in snap.animations.iter().enumerate() {
                let _ = anims.set(i + 1, name.as_str());
            }
            let _ = t.set("animations", anims);
            let _ = entities_table.set(*id, t);
        }
        let _ = globals.set("entities", entities_table);
    }

    fn build_entity_table(&self, entity_id: u32, snap: Option<&EntitySnapshot>) -> LuaResult<LuaTable> {
        let t = self.lua.create_table()?;
        t.set("id", entity_id)?;
        if let Some(s) = snap {
            t.set("x",       s.x)?;
            t.set("y",       s.y)?;
            t.set("scale_x", s.scale_x)?;
            t.set("scale_y", s.scale_y)?;
            let anims = self.lua.create_table()?;
            for (i, name) in s.animations.iter().enumerate() {
                anims.set(i + 1, name.as_str())?;
            }
            t.set("animations", anims)?;
        }
        Ok(t)
    }

    fn call_lifecycle(&self, table: &LuaTable, method: &str, entity_id: u32) {
        if let Ok(f) = table.get::<LuaFunction>(method) {
            let entity_table = self.lua.create_table().expect("entity table");
            let _ = entity_table.set("id", entity_id);
            if let Err(e) = f.call::<()>((table.clone(), entity_table)) {
                log::warn!("[scripting] {}: {}", method, e);
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Lua call helpers (free functions to avoid borrow issues)
// ---------------------------------------------------------------------------

fn call_fn(table: &LuaTable, method: &str, entity: LuaTable) -> LuaResult<()> {
    match table.get::<LuaValue>(method)? {
        LuaValue::Function(f) => f.call::<()>((table.clone(), entity)),
        LuaValue::Nil => Ok(()), // method not defined — skip silently
        _ => Ok(()),
    }
}

fn call_fn_dt(table: &LuaTable, method: &str, entity: LuaTable, dt: f32) -> LuaResult<()> {
    match table.get::<LuaValue>(method)? {
        LuaValue::Function(f) => f.call::<()>((table.clone(), entity, dt)),
        LuaValue::Nil => Ok(()),
        _ => Ok(()),
    }
}

/// Push a command table into the global __cmds queue.
fn push_cmd<F>(lua: &Lua, kind: &str, fill: F) -> LuaResult<()>
where
    F: FnOnce(&LuaTable) -> LuaResult<()>,
{
    let queue: LuaTable = lua.globals().get("__cmds")?;
    let cmd = lua.create_table()?;
    cmd.set("kind", kind)?;
    fill(&cmd)?;
    let len = queue.raw_len();
    queue.raw_set(len + 1, cmd)?;
    Ok(())
}

/// Parse a cmd table from Lua into a ScriptCmd.
fn parse_cmd_table(t: LuaTable) -> LuaResult<ScriptCmd> {
    let kind: String = t.get("kind")?;
    match kind.as_str() {
        "move_to" => Ok(ScriptCmd::SetPosition {
            id: t.get("id")?,
            x:  t.get("x")?,
            y:  t.get("y")?,
        }),
        "translate" => Ok(ScriptCmd::Translate {
            id: t.get("id")?,
            dx: t.get("dx")?,
            dy: t.get("dy")?,
        }),
        "set_scale" => Ok(ScriptCmd::SetScale {
            id: t.get("id")?,
            sx: t.get("sx")?,
            sy: t.get("sy")?,
        }),
        "play_animation" => Ok(ScriptCmd::PlayAnimation {
            id:   t.get("id")?,
            name: t.get("name")?,
        }),
        "stop_animation" => Ok(ScriptCmd::StopAnimation {
            id: t.get("id")?,
        }),
        "set_physics" => Ok(ScriptCmd::SetPhysics {
            id:        t.get("id")?,
            enabled:   t.get("enabled")?,
            body_type: t.get("body_type")?,
        }),
        "move_entity" => Ok(ScriptCmd::MoveEntity {
            id:    t.get("id")?,
            speed: t.get("speed")?,
            dir_x: t.get("dir_x")?,
            dir_y: t.get("dir_y")?,
        }),
        "stop_entity" => Ok(ScriptCmd::StopEntity {
            id: t.get("id")?,
        }),
        "log" => Ok(ScriptCmd::Log {
            message: t.get("message")?,
        }),
        other => Err(LuaError::runtime(format!("unknown script cmd: {other}"))),
    }
}
